DELETE http://localhost:4000/api/employee?employeeId=
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJrZXkiOiIzYjRlMDBiZS0wNDVmLTQ1MmMtOWU4NC02ZWJjZTZmMzY0NTIiLCJpZCI6IjllZTJjZDU5LTY1NDQtNDI0Zi04NGI0LTIyNjVkMTA4Y2RjNyIsInR5cGUiOiJWRU5ET1IiLCJpYXQiOjE2NzAxMjE5MTJ9.ATYDyciphY9d-N46CWyKzP3hBf-ReKxubHTrrjZrGNg