POST http://localhost:4000/api/tempImage
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJrZXkiOiIxODI2Mzg4Yy1kZDBiLTRhMDAtYTRiYy1kMWRjOTBkOGFmODEiLCJpZCI6ImM2NGQ4MmE3LTBmZWEtNDQ5YS05ZTJjLTQ5MzczYTJmNjM5YyIsInR5cGUiOiJBRE1JTiIsImlhdCI6MTY3MDExMTE4OX0.bozYd-Oroy7Hi_Es9cng2k6uoJSp4K9xiDxIXWXhWLc
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="dog.jpeg"
Content-Type: image/jpg

< ./images/dog.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--