POST http://localhost:4000/api/employee
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJrZXkiOiIxODI2Mzg4Yy1kZDBiLTRhMDAtYTRiYy1kMWRjOTBkOGFmODEiLCJpZCI6ImM2NGQ4MmE3LTBmZWEtNDQ5YS05ZTJjLTQ5MzczYTJmNjM5YyIsInR5cGUiOiJBRE1JTiIsImlhdCI6MTY3MDExMTE4OX0.bozYd-Oroy7Hi_Es9cng2k6uoJSp4K9xiDxIXWXhWLc

{
  "name": "Carlos",
  "surname": "Martinez",
  "email": "pedro@gmail.com",
  "nroDocument": "1002223334",
  "birthDate": "1670099281733",
  "imageURL": "http://localhost:4000/api/tempImage/ae8b2234-f673-4a4e-b7f0-0a2802c06d65",
  "accessCode": "123456",
  "type": "VENDOR",
  "phone": "3116537527"
}
